### ISSUE TITLE
Not able to retrive views from disabled users!

### ISSUE THREAD

**Issue by ThorTankred** [carfup/XTBPlugins.PersonalViewsMigration#1]
Hi,

We have an 8.2 Dynamics365 solution.
We have disabled users, with shared personal views, and we would like to transfer/delete them.
But it seems that the plugin, is NOT able to retrieve views from disabled users?

**Comment by carfup** [comment]
Hi ThorTankred,

Thanks for your feedback.
First question, are you using Dyn365 onprem or online ?

I figured out yesterday that the way i'm managing the disabled users can't work that way on the onprem environements ... I'm trying to find a workaround in order to provide the functionality onprem too.

If you are online, can you please tell me if you have any errors ? Make sure that the disabled users is still in the AAD (deleted, since after 30 days of deletion, it's not possible anymore to impersonate).

Thanks

**Comment by ThorTankred** [comment]
Hi,

We have a 8.2 DYN365 online solution.
But I am not able to find the user in O365 admin center, so it could be due to the 30day rule.

/Thor

**Comment by carfup** [comment]
Hi Thor, 

Thanks for your answer.
Then if your user is completely removed from the O365 admin center (even from the recycle bin), then unfortunately, your only solution is to ask MS directly.

I close the ticket as i don't have any power here but feel free to reopen it in case of).

Thanks for using the plugin.
Regards,
